### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by altela** [Altela/odoo-api#15]
Below is To-Do list of this repo.
If a list has errors or bug, open an Issues and put it's number beside related list below.

Script to Create New Record
- [X] Sales Order & Quotation #8
- [X] Memo
- [X] Partner
- [X] Master Products
- [X] Purchase RFQ - #13
- [X] Helpdesk Ticket
- [ ] Sales Invoice
- [ ] Accounting Credit Notes
- [ ] Accounting Payments
- [ ] Accounting Refund
- [ ] Accounting Journal Entries
- [ ] Accounting Journal Items
- [ ] Accounting Assets
- [ ] Inventory Transfers
- [ ] Inventory Adjustments
- [ ] Inventory Scraps
- [ ] PoS Orders
- [ ] Pos Session
- [ ] Manufacturing Orders
- [ ] Manufacturing Unbuild Orders
- [ ] Manufacturing Scrap Orders
- [ ] Manufacturing Bill of Materials
- [ ] Employee Name
- [ ] Employee Department Status
- [x] Attendance
- [ ] Expenses & Expenses Reports
- [ ] Lunch
- [ ] Fleet

Script to Show a List of Something
- [X] Show Partner
- [X] Show Master Product
- [ ] TBD

Script to Change a Record's Status (Validate, Draft, Cancelled)
- [ ] Sales Quotation Status
- [ ] RFQ Status
- [ ] Master Product Archive Status
- [ ] Quotation Status
- [ ] Helpdesk Status Update
- [ ] TBD
